--- #YAML:1.0
name:                Catalyst-Model-SVN
version:             0.13
abstract:            Catalyst Model to browse Subversion repositories
license:             ~
author:              
    - Christopher H. Laco <claco@chrislaco.com>, Tomas Doran <bobtfish@bobtfish.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Catalyst::Devel:               0
    Catalyst::Runtime:             0
    DateTime:                      0
    IO::Scalar:                    0
    Path::Class:                   0
    SVN::Core:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
